# Generated by Django 4.2.3 on 2024-01-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='old_price',
            field=models.FloatField(null=True),
        ),
    ]
