# Generated by Django 4.2.3 on 2024-01-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_book_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='old_price',
        ),
    ]
