# Generated by Django 4.2.3 on 2024-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_author_slug_book_slug_genre_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
