# Generated by Django 4.2.3 on 2024-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.ImageField(default='default_author.jpeg', upload_to='author_portraits'),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
