# Generated by Django 4.2.3 on 2024-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
