# Generated by Django 4.2.9 on 2024-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_book_image_alter_book_image_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=100, null=True),
        ),
    ]
