# Generated by Django 4.2.9 on 2024-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(help_text='width 300px', upload_to='book_covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_preview',
            field=models.ImageField(help_text='height 310px', upload_to='book_covers'),
        ),
    ]
