# Generated by Django 4.2.9 on 2024-08-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_book_image_alter_book_image_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_preview',
        ),
    ]
