# Generated by Django 4.2.9 on 2024-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_book_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_preview',
            field=models.ImageField(blank=True, help_text='height 310px', null=True, upload_to='book_covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='width 300px', null=True, upload_to='book_covers'),
        ),
    ]
