# Generated by Django 4.2.9 on 2024-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_book_on_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
