# Generated by Django 4.2.9 on 2024-08-31 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_book_id_bestseller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="id_bestseller",
            new_name="is_bestseller",
        ),
    ]
